### ISSUE TITLE
Метод containsGame не показывает добавленную игру

### ISSUE THREAD

**Issue by Mutafrukt** [Mutafrukt/Team_QA_v1#1]
# Описание
Метод containsGame в классе GameStore не находит добавленную в каталог игру, если она одна. Также метод не показывает последнюю игру в списке, если было добавлено несколько игр

# Локация дефекта
https://github.com/Mutafrukt/Team_QA_v1/blob/faa2bc1cfc455d6c07ef55cfd432de16013e78bd/src/main/java/ru/netology/GameStore.java#L34-L36

# Шаги воспроизведения

1. Открыть [код GameStoreTest](https://github.com/Mutafrukt/Team_QA_v1/blob/main/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2. Создать объект класса  GameStore
3. Через метод publishGame добавить коллекцию игр
4. Вызов метода ContainsGame проверить с помощью AssertTrue
5. Запустить тест shouldContainsAddedGameIfOneGame

*Ожидаемый результат:* TRUE
*Фактический результат:* FALSE

# Скриншот
<img width="1093" alt="Снимок экрана 2022-08-22 в 19 11 23" src="https://user-images.githubusercontent.com/105596094/185968624-6f486267-60b0-4a66-b997-ecfdb7c5e4bf.png">

# Окружение
ОС - macOS Monterey 12.6
IntelliJ IDEA 2022.1.3 (Community Edition)
Java 11.0.15

**Comment by Pavel-Ole** [comment]
Ошибка исправлена была в счетчике for (int i = 1; i <= games.size(); i++)
