### ISSUE TITLE
Метод getMostPlayer не возвращает игрока

### ISSUE THREAD

**Issue by Mutafrukt** [Mutafrukt/Team_QA_v1#3]
# Описание

Метод getMostPlayer не возвращает игрока, проигравшего больше времени, если он играл один час. При игре больше часа метод работает

# Локация дефекта
https://github.com/Mutafrukt/Team_QA_v1/blob/e65852b64c1a5a7e503368cf557d0e9ad2b6b5cd/src/main/java/ru/netology/GameStore.java#L58-L62

# Шаги воспроизведения

1. Открыть [код GameStoreTest](https://github.com/Mutafrukt/Team_QA_v1/blob/main/src/test/java/ru/netology/GameStoreTest.java) в Idea
2. Создать объект класса GameStore
3. Добавить игроков и их время через addPlayTime
4. Запустить тест, посмотреть на результат

*Ожидаемый результат:* Mingus
*Фактический результат:* Null

# Скриншот

<img width="796" alt="Снимок экрана 2022-08-23 в 15 47 58" src="https://user-images.githubusercontent.com/105596094/186161983-5d43ce33-115e-4a75-a9ce-f46163bed04f.png">

# Окружение
ОС - macOS Monterey 12.6
IntelliJ IDEA 2022.1.3 (Community Edition)
Java 11.0.15

**Comment by Pavel-Ole** [comment]
Исправлено в коде int mostTime = 0
