### ISSUE TITLE
Класс Player метод play нет оповещения что игра не установлена

### ISSUE THREAD

**Issue by Pavel-Ole** [Mutafrukt/Team_QA_v1#5]
# Описание
В методе play нет кода на выкидывание исключение RuntimeException

# Локация дефекта
https://github.com/Mutafrukt/Team_QA_v1/blob/e65852b64c1a5a7e503368cf557d0e9ad2b6b5cd/src/main/java/ru/netology/Player.java#L33-L41

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Mutafrukt/Team_QA_v1) в IDEA
2. Зайти в класс Player
3. Найти метод play

*Ожидаемый результат:* В методе play написан код на исключение RuntimeException
*Фактический результат:* В методе play кода на исключение RuntimeException отсутствует

# Скриншот
![Screenshot_46](https://user-images.githubusercontent.com/106340733/186252713-0093c5a8-c79b-40fc-9539-0b829046d65a.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2020,2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Mutafrukt** [comment]
в код внесены изменения
