### ISSUE TITLE
Класс Player метод sumGenre не суммирует время.

### ISSUE THREAD

**Issue by Pavel-Ole** [Mutafrukt/Team_QA_v1#6]
# Описание
Метод sumGenre всегда выводит 0 проигранного времени в жанре

# Локация дефекта
https://github.com/Mutafrukt/Team_QA_v1/blob/e65852b64c1a5a7e503368cf557d0e9ad2b6b5cd/src/main/java/ru/netology/Player.java#L50-L52

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Mutafrukt/Team_QA_v1) в IDEA
2. Открыть класс PlayerTest
3. Сделать тест public void shouldSumGenreDifferentTwoGame()

*Ожидаемый результат:* Суммарное время игры одного жанра должно быть 8 часов
*Фактический результат:* Суммарное время игры одного жанра выдает 0 часов

# Скриншот
![Screenshot_47](https://user-images.githubusercontent.com/106340733/186447869-9c8cde62-925c-4097-89b4-69f5104d718c.png)
![Screenshot_48](https://user-images.githubusercontent.com/106340733/186447870-17a4e91c-04b2-4345-a3f0-51d30fe2667c.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Mutafrukt** [comment]
Исправлен код
