### ISSUE TITLE
Класс Player метод mostPlayerByGenre не написан полностью код

### ISSUE THREAD

**Issue by Pavel-Ole** [Mutafrukt/Team_QA_v1#7]
# Описание
В методе mostPlayerByGenre не написан код на возвращение игры в которую играли больше всего

# Локация дефекта
https://github.com/Mutafrukt/Team_QA_v1/blob/e65852b64c1a5a7e503368cf557d0e9ad2b6b5cd/src/main/java/ru/netology/Player.java#L59

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Mutafrukt/Team_QA_v1) в IDEA
2. Открыть класс Player
3. Найти метод mostPlayerByGenre

*Ожидаемый результат:* Написанный полностью код по ТЗ
*Фактический результат:* Написанный код только на возврат "null"

# Скриншот
![Screenshot_49](https://user-images.githubusercontent.com/106340733/186454668-43f40b58-2f9e-44c9-bba5-8053e5e12c86.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelleJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Mutafrukt** [comment]
Метод дописан
